addons:
  firefox: latest
sudo: false
language: node_js
node_js:
- '5.0'
env:
  global:
  - DISPLAY=:99.0
  - GH_REF: github.com/FineUploader/modern-uploader
  - secure: 5VbvxRylDk89JE8SFZtQKFvVLgcI83LKTspAgArSial+fPrubNlusthfTysMSm47n2Xa5Opgolibgo4Qc7jHfX/Byu/NTPrU8SX+DJOmVDm2nUfhl4qi13ughwjKyO9Ks8avJwQNcsJhxvPISyJrVnSWFWsUJe0kloAVBQO+yTKYABBt54KbHBM5nnB5Wz/lfnEwvirvNwkgkcGsPB4+SAqRjirQUjjHN1hfIA9zpj7lApHYs0zSNeIwOhdLF3hxCR7odxF6wGgpp9C2bnzuG1qWyY6KBEXfgHI2WwA7lewJFWki+2OEEIUkamwBViHVX02P80iTrqVwlRK7mYdnY/LHtjVg7XcOBP6fl1j6xYfKFPOom329o0KI9s7ZvKtNvuLF1fAlZnGVuP695VeAmKCygC4qG7C/YB47crZDppGu7W2VBxDc1hOqGI59+mnNy0LJF2WGLkOzqmHJtrcDrGPu0sfMiNTVb6cWhXnbtjSGZJpM3UTv5TxxWg1TwqX7UWjDLt7P8eC3W05lH4gP+lsiBVvu+3qfG5jHxJgGaDt7vPzqVczyJWK1gnFywwe7TTbsMlGAIOgBw+LAzTYfWsy/D+Hl7VygBjLnbXkivpvu8kSFeTdPNtCnG2tsTw4wsumH1Pu00NuKU1gWB40Ze5Q5ZjmcO0/qN17WpFk3f/M=
before_script:
- sh -e /etc/init.d/xvfb start
notifications:
  slack:
    on_success: change
    rooms:
      secure: UOtSTJJgQ6OR3E2PQlfcmAjb9xrHWSNRlUMTpZ6AdAW1UCi51vqrkGXGJ0KQDju06LoLlPWVfA8J1RJVJE+vVUXOcIRv1esFpmJmS8yhOnbdzsbbjOpdPq0ihEh0qA9EecchZV+ILYRVXcuO6tH2ROWAXW2zqaYJfzhE/Ax7ZmH4DPpVUb6jpmdX50aLN0ejXnzD31WXDKvCa/oBvBZAqjx1EA6V83t9A50VKkLmE+FReQaWxXCuUoJg+Pfs5kFfOi1jAVWwq3A9kiPcQe+BJXdvOae1IOiQnik+kzPay8tYVINfg0xDxs1sIiXrZPY43NVIpJLq6ZT9J9Kp2k1hnLFBX8ooUNZ8/sigN/YaQu+1c6+A7yiY91RFk8dEgVemDlVdiLkhGkgrWZMWyW4v/WGb3k6FoPiAW+TizOPRMvg7QGDTc52mMtS6HrXRMZge498ELbl7H0oA9JNpBp8fkXl7w1LVUH84klNVSjZpTHRXjk46wGSypfsOpoyby4zXMku8XAlmALg0IwDnwOhh+XIRBwp+I3zNiHgmZYF3N1UQqldi/0ICixmxbJMbDatymL5gvP960N/b9T0o7Ub3V9/WzlzdsrHIZ8bPOvn8YdmHMFMuLHjN753c5sjmPZQFUK9wo+hTHMGoEJu7Iig8xvSK7eVa8qqPSeDx5dNu/Og=
after_success:
- make publishDocs
